### ISSUE TITLE
[PLGPRSS17-11] Error with tax_table_selector in Payment controller

### ISSUE THREAD

**Issue by morgan-enetb** [MultiSafepay/Prestashop#5]
Configuration :
- Pretashop 1.7.2.1
- MultiSafepay module

When no tax is configured or if intra-Community VAT is configured, nothing is set in "tax_table_selector" in payement controller (Prestashop return nothing), so we get error on multisafepay page.

I use workaround by override product class and set 'no-tax' if field is empty but i don't think is the best way.

**Comment by Jasper-MultiSafepay** [comment]
Thanks for reporting this.
The current proposed workaround we have is to set a tax rule for your products within Prestashop.
But I will be discussing this further with the plugin developer, if we could improve the check on
https://github.com/MultiSafepay/Prestashop/blob/master/controllers/front/payment.php#L275

if $product['tax_name'] would be empty, we could just set a tax table of 0.00

**Comment by Jasper-MultiSafepay** [comment]
Workaround is no longer needed => Fixed in 4.7.0
