### ISSUE TITLE
Problem with sorting modules.

### ISSUE THREAD

**Issue by mark-app** [MultiSafepay/Prestashop#6]
Problem with sorting modules on PHP 7.1

Warning: A non-numeric value encountered in multisafepay.php line 144. at usort.

Change this on line 144.

return $a['sort'] - $b['sort'];

To this:

return (int)$a['sort'] - (int)$b['sort'];

**Comment by Jasper-MultiSafepay** [comment]
@mark-app 
Thanks for reporting this.
We will include this in the next version of the plugin.
PLGPRSS-304

**Comment by Jasper-MultiSafepay** [comment]
Fixed in https://github.com/MultiSafepay/PrestaShop/releases/tag/4.3.0
PLGPRSS-347: Fix warning during sorting of gateways and giftcards
